[package]
name = "select_reset_test"
version = "0.1.0"
authors = ["Chris Ricketts <chris.ricketts@steribar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.8.0"
web_logger = "0.1.0"
log = "0.4"
